from __future__ import annotations

import json
import re
import sys
from datetime import datetime, timezone
from dataclasses import dataclass
from pathlib import Path
from typing import List, Tuple

from PIL import Image, ImageOps


@dataclass(frozen=True)
class RenameSuggestion:
    source: Path
    target_name: str


@dataclass(frozen=True)
class StrictRenamePlan:
    suggestions: List[RenameSuggestion]
    missing_fronts: List[str]
    duplicate_back_keys: List[str]
    already_matched: int


@dataclass(frozen=True)
class RenameAction:
    source: Path
    target: Path


@dataclass(frozen=True)
class RenameExecutionResult:
    applied: int
    dry_run: bool
    actions: List[RenameAction]
    skipped_same_name: int
    conflicts: List[str]


@dataclass(frozen=True)
class UndoExecutionResult:
    applied: int
    dry_run: bool
    actions: List[RenameAction]
    conflicts: List[str]
    no_history: bool


def _ps_quote(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def build_powershell_rename_script(*, plan: StrictRenamePlan, back_dir: Path) -> str:
    lines: List[str] = []
    lines.append("# Auto-generated by Planechase ProxyGen (strict pairing suggestions)")
    lines.append("# Review before running. This script renames files in-place.")
    lines.append("$ErrorActionPreference = 'Stop'")
    lines.append(f"Set-Location {_ps_quote(str(back_dir))}")
    lines.append("")

    if plan.duplicate_back_keys:
        lines.append("# Duplicate normalized back-name keys detected:")
        for key in plan.duplicate_back_keys:
            lines.append(f"# - {key}")
        lines.append("")

    if not plan.suggestions:
        lines.append("# No rename suggestions were generated.")
        return "\n".join(lines) + "\n"

    lines.append("# Suggested renames:")
    for item in plan.suggestions:
        old_name = item.source.name
        new_name = item.target_name
        if old_name == new_name:
            lines.append(f"# SKIP (already matching): {old_name}")
            continue
        lines.append(f"Rename-Item -LiteralPath {_ps_quote(old_name)} -NewName {_ps_quote(new_name)}")

    if plan.missing_fronts:
        lines.append("")
        lines.append("# Missing backs for fronts (manual action needed):")
        for name in plan.missing_fronts:
            lines.append(f"# - {name}")

    return "\n".join(lines) + "\n"


def write_powershell_rename_script(*, path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def apply_strict_rename_plan(*, plan: StrictRenamePlan, back_dir: Path, apply_changes: bool) -> RenameExecutionResult:
    actions: List[RenameAction] = []
    conflicts: List[str] = []
    skipped_same_name = 0

    existing_sources = {item.source.name.lower() for item in plan.suggestions}

    for item in plan.suggestions:
        source_path = back_dir / item.source.name
        target_path = back_dir / item.target_name

        if item.source.name.lower() == item.target_name.lower():
            skipped_same_name += 1
            continue

        if not source_path.exists():
            conflicts.append(f"Missing source file: {item.source.name}")
            continue

        if target_path.exists() and target_path.resolve() != source_path.resolve():
            if target_path.name.lower() not in existing_sources:
                conflicts.append(f"Target already exists: {target_path.name}")
                continue

        actions.append(RenameAction(source=source_path, target=target_path))

    if not apply_changes or conflicts:
        return RenameExecutionResult(
            applied=0,
            dry_run=True,
            actions=actions,
            skipped_same_name=skipped_same_name,
            conflicts=conflicts,
        )

    applied = 0
    for action in actions:
        action.source.rename(action.target)
        applied += 1

    return RenameExecutionResult(
        applied=applied,
        dry_run=False,
        actions=actions,
        skipped_same_name=skipped_same_name,
        conflicts=conflicts,
    )


def append_rename_history_entry(*, history_path: Path, back_dir: Path, actions: List[RenameAction]) -> None:
    history_path.parent.mkdir(parents=True, exist_ok=True)
    payload = {
        "timestamp_utc": datetime.now(timezone.utc).isoformat(),
        "back_dir": str(back_dir.resolve()),
        "actions": [
            {
                "source": action.source.name,
                "target": action.target.name,
            }
            for action in actions
        ],
    }
    with history_path.open("a", encoding="utf-8") as f:
        f.write(json.dumps(payload, ensure_ascii=False) + "\n")


def undo_last_rename_batch(*, history_path: Path, back_dir: Path, apply_changes: bool) -> UndoExecutionResult:
    if not history_path.exists():
        return UndoExecutionResult(applied=0, dry_run=True, actions=[], conflicts=[], no_history=True)

    raw_lines = history_path.read_text(encoding="utf-8").splitlines()
    parsed_entries: List[tuple[int, dict]] = []
    for idx, line in enumerate(raw_lines):
        stripped = line.strip()
        if not stripped:
            continue
        try:
            entry = json.loads(stripped)
        except Exception:
            continue
        parsed_entries.append((idx, entry))

    back_dir_resolved = str(back_dir.resolve())
    target_entry_idx = -1
    target_entry: dict | None = None

    for idx, entry in reversed(parsed_entries):
        if str(entry.get("back_dir", "")) == back_dir_resolved:
            target_entry_idx = idx
            target_entry = entry
            break

    if target_entry is None:
        return UndoExecutionResult(applied=0, dry_run=True, actions=[], conflicts=[], no_history=True)

    actions_raw = target_entry.get("actions", [])
    reverse_actions: List[RenameAction] = []
    conflicts: List[str] = []

    for item in reversed(actions_raw):
        src_name = str(item.get("source", "")).strip()
        dst_name = str(item.get("target", "")).strip()
        if not src_name or not dst_name:
            continue

        undo_source = back_dir / dst_name
        undo_target = back_dir / src_name

        if not undo_source.exists():
            conflicts.append(f"Missing source file for undo: {undo_source.name}")
            continue

        if undo_target.exists() and undo_target.resolve() != undo_source.resolve():
            conflicts.append(f"Undo target already exists: {undo_target.name}")
            continue

        reverse_actions.append(RenameAction(source=undo_source, target=undo_target))

    if not apply_changes or conflicts:
        return UndoExecutionResult(
            applied=0,
            dry_run=True,
            actions=reverse_actions,
            conflicts=conflicts,
            no_history=False,
        )

    applied = 0
    for action in reverse_actions:
        action.source.rename(action.target)
        applied += 1

    new_lines: List[str] = []
    for idx, line in enumerate(raw_lines):
        if idx == target_entry_idx:
            continue
        new_lines.append(line)

    if new_lines:
        history_path.write_text("\n".join(new_lines) + "\n", encoding="utf-8")
    else:
        history_path.unlink(missing_ok=True)

    return UndoExecutionResult(
        applied=applied,
        dry_run=False,
        actions=reverse_actions,
        conflicts=[],
        no_history=False,
    )


def _pick_highest_resolution_back(backs: List[Path]) -> Path | None:
    best = None
    best_area = -1

    for p in backs:
        try:
            with Image.open(p) as source:
                im = ImageOps.exif_transpose(source) or source
                w, h = im.size
            area = int(w) * int(h)
        except Exception:
            continue

        if area > best_area:
            best_area = area
            best = p

    return best


def _normalize_name_key(stem: str) -> str:
    key = stem.lower().strip()
    key = re.sub(r"[^a-z0-9]+", "", key)
    for suffix in ("back", "rewers", "tyl", "reverse"):
        if key.endswith(suffix):
            key = key[: -len(suffix)]
    return key


def _match_backs_by_name(fronts: List[Path], backs: List[Path]) -> Tuple[List[Path] | None, List[str], List[str]]:
    buckets: dict[str, List[Path]] = {}
    for bp in backs:
        k = _normalize_name_key(bp.stem)
        buckets.setdefault(k, []).append(bp)

    duplicates = [k for k, vals in buckets.items() if len(vals) > 1]
    if duplicates:
        return None, [f"duplicate-back-key:{k}" for k in duplicates], []

    used_keys: set[str] = set()
    mapped: List[Path] = []
    missing: List[str] = []

    for fp in fronts:
        k = _normalize_name_key(fp.stem)
        found = buckets.get(k)
        if not found:
            missing.append(fp.name)
            continue
        used_keys.add(k)
        mapped.append(found[0])

    extras = [p.name for k, vals in buckets.items() if k not in used_keys for p in vals]
    if missing:
        return None, missing, extras
    return mapped, [], extras


def build_strict_rename_plan(fronts: List[Path], backs: List[Path]) -> StrictRenamePlan:
    buckets: dict[str, List[Path]] = {}
    for bp in backs:
        key = _normalize_name_key(bp.stem)
        buckets.setdefault(key, []).append(bp)

    duplicate_keys = sorted([k for k, vals in buckets.items() if len(vals) > 1])

    matched_front_names: set[str] = set()
    used_back_paths: set[Path] = set()

    for fp in fronts:
        key = _normalize_name_key(fp.stem)
        vals = buckets.get(key, [])
        if len(vals) == 1:
            matched_front_names.add(fp.name)
            used_back_paths.add(vals[0])

    unmatched_fronts = [fp for fp in fronts if fp.name not in matched_front_names]

    unmatched_backs: List[Path] = []
    for key, vals in buckets.items():
        if key in duplicate_keys:
            unmatched_backs.extend(vals)
            continue
        if vals[0] not in used_back_paths:
            unmatched_backs.append(vals[0])

    unmatched_fronts.sort(key=lambda p: p.name.lower())
    unmatched_backs.sort(key=lambda p: p.name.lower())

    suggestions: List[RenameSuggestion] = []
    for back_path, front_path in zip(unmatched_backs, unmatched_fronts):
        target = f"{front_path.stem}_back{back_path.suffix.lower()}"
        suggestions.append(RenameSuggestion(source=back_path, target_name=target))

    missing_fronts = [p.name for p in unmatched_fronts[len(suggestions):]]

    return StrictRenamePlan(
        suggestions=suggestions,
        missing_fronts=missing_fronts,
        duplicate_back_keys=duplicate_keys,
        already_matched=len(matched_front_names),
    )


def build_back_list(fronts: List[Path], backs: List[Path], *, back_pairing: str) -> List[Path]:
    if len(backs) == 0:
        raise ValueError("Back folder contains no images")
    if len(backs) == 1:
        return [backs[0]] * len(fronts)

    pairing = back_pairing.lower().strip()
    if pairing not in {"smart", "strict"}:
        raise ValueError("back_pairing must be smart|strict")

    matched, missing, extras = _match_backs_by_name(fronts, backs)
    if matched is not None:
        if extras:
            print(
                f"[WARN] Unused back images after name matching: {', '.join(extras[:6])}{' ...' if len(extras) > 6 else ''}",
                file=sys.stderr,
            )
        return matched

    if pairing == "strict":
        if missing and missing[0].startswith("duplicate-back-key:"):
            dupe_keys = [m.split(":", 1)[1] for m in missing]
            raise ValueError(
                "Strict back pairing failed: duplicate back name keys detected: "
                + ", ".join(dupe_keys)
                + ". Rename back files so each card has a unique normalized name."
            )
        raise ValueError(
            "Strict back pairing failed: missing back image for front(s): "
            + ", ".join(missing[:8])
            + (" ..." if len(missing) > 8 else "")
        )

    if len(backs) != len(fronts):
        best = _pick_highest_resolution_back(backs)

        if best is None:
            raise ValueError(
                f"Back images count must be 1 or equal to front count, and no readable back images found. fronts={len(fronts)} backs={len(backs)}"
            )

        miss_preview = ", ".join(missing[:4]) if missing else "name mismatch"
        print(
            f"[WARN] Back pairing smart fallback ({miss_preview}). Back folder has {len(backs)} images but fronts={len(fronts)}. "
            f"Using the highest-resolution back for all: {best.name}",
            file=sys.stderr,
        )
        return [best] * len(fronts)

    print(
        "[WARN] Back names do not match front names; using sorted 1:1 pairing by filename order.",
        file=sys.stderr,
    )
    return backs
